### ISSUE TITLE
repeatable crush on world load in itme primal bracelet and blink foci from Forbidden Magic

### ISSUE THREAD

**Issue by adamsonich** [Modbder/ThaumicBases#11]
I have repeatable crush when load save with primal bracelet and blink foci from Forbidden Magic

Description: Rendering item
java.lang.NullPointerException: Rendering item
    at tb.client.render.item.CastingBraceletRenderer.renderItem(CastingBraceletRenderer.java:189)
    at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:183)

 

i have no problems to use it ingame, but if i quit and run MC then i have that error. if I save and load world then no crush happen.

use Forbidden Magic-1.7.10-0.57 and ThaumicBases-1.3.1710.4

**Comment by adamsonich** [comment]
but if I first load world where i have not bracelet in hotbar then "crushed" world loads correctly.
If i move bracelet from hotbar then world loads correctly.

**Comment by Modbder** [comment]
Well, I need more information on this one - this error should be impossible... 

Does the crash only happen with the ForbiddenMagic's Blink foci, or is this with any other foci?
What mods(especially ASM coremods) do you have installed?

**Comment by adamsonich** [comment]
asm core mods not installed at all
full list of mods: http://clip2net.com/s/3noavYD
other foci will test late

**Comment by Modbder** [comment]
You do have a lot of asm coremods installed though. Asm core mods are not the mods you need to insert into jar file - they are mods that dynamically change code as the game loads. I've asked about that because that error should not be possible.

Let's see....
Well, apart from a lot of horribly outdated mods I don't see anything suspicious that may cause this crash. Though I'm interested in 2 files of yours - what are ja1r files? Never seen them before. Is there a special mod loader for those, or are they just 'disabled mods'?

I can't compile any of my mods for now, so I can't give you a test version sadly.

**Comment by adamsonich** [comment]
if U rename *.jar to *.ja1r then that mod will not be loaded.

**Comment by Modbder** [comment]
Oh, come on. This random crash again? That I believe is a DummyCore issue, but I can't figure out what causes it. The fact that it is extremely random and occurs for 1/10000 people and the fact, that I can't replicate it no matter what I do?..
Later version of DummyCore will have an option to disable it's custom main menu feature(i believe that it is the cause here) but for now there is really nothing I(and you too) can do with this one.

**Comment by adamsonich** [comment]
so maybe and my first error has some issue? I will close issue and will wait for update.

**Comment by Modbder** [comment]
Sure. Be free to open it again once I release a new version and those issues are not gone. Though I believe that your original TB issue is solved.
