### ISSUE TITLE
[1.7.10] MFR cannot properly detect Plax as a crop for Harvesters

### ISSUE THREAD

**Issue by Shadows-of-Fire** [Modbder/ThaumicBases#17]
According to previous sources, this is usually an error on the side of the crop, where it is not properly defined as a plant or something of the sort. Waila also does not show growth %.

**Comment by Modbder** [comment]
That happens since TB's crops extend the BlockBush rather than BlockCrops. I still return EnumPlantType.Crop with a getPlantType method, but I guess that is not a thing MFR checks for. I can implement a WAILA fix/plugin in order to make it show growth %, but I do not know about MFR - does it have an API for that sort of things?

**Comment by Modbder** [comment]
I've checked MFR's github and indeed, they do have an API for that. When 1.8 version of MFR's API will be released I will make sure to add those interfaces to my plants to make them compatible with MFR(assuming the issue will still be existing at that point). I will leave this issue open, but if you want - feel free to close it

**Comment by Shadows-of-Fire** [comment]
As far as I know MFR and the other CoFH mods currently have no plans to hit 1.8, so if you had the free time could you implement that into the 1.7 version?

**Comment by Shadows-of-Fire** [comment]
rip 1.7
